Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job        count
-------  -------
vep_vcf        1
total          1

Select jobs to execute...
Execute 1 jobs...

[Tue May 21 14:46:53 2024]
localrule vep_vcf:
    input: /data2/mbaragli/python_app/app_python/work_dir/testrun_4_HG002/snv/testrun_4_HG002_longshot.vcf
    output: /data2/mbaragli/python_app/app_python/work_dir/vep_database/snv/vep_database_vep.vcf
    log: /data2/mbaragli/python_app/app_python/work_dir/vep_database/logs/vep.log
    jobid: 0
    reason: Missing output files: /data2/mbaragli/python_app/app_python/work_dir/vep_database/snv/vep_database_vep.vcf
    wildcards: sample=vep_database
    threads: 8
    resources: tmpdir=/tmp

vep -format vcf -i /data2/mbaragli/python_app/app_python/work_dir/testrun_4_HG002/snv/testrun_4_HG002_longshot.vcf -o /data2/mbaragli/python_app/app_python/work_dir/vep_database/snv/vep_database_vep.vcf --vcf --fork 8 --assembly GRCh38 --everything --database    --offline False 
Activating conda environment: vep
[Tue May 21 14:46:54 2024]
Error in rule vep_vcf:
    jobid: 0
    input: /data2/mbaragli/python_app/app_python/work_dir/testrun_4_HG002/snv/testrun_4_HG002_longshot.vcf
    output: /data2/mbaragli/python_app/app_python/work_dir/vep_database/snv/vep_database_vep.vcf
    log: /data2/mbaragli/python_app/app_python/work_dir/vep_database/logs/vep.log (check log file(s) for error details)
    conda-env: vep
    shell:
        vep -format vcf -i /data2/mbaragli/python_app/app_python/work_dir/testrun_4_HG002/snv/testrun_4_HG002_longshot.vcf -o /data2/mbaragli/python_app/app_python/work_dir/vep_database/snv/vep_database_vep.vcf --vcf --fork 8 --assembly GRCh38 --everything --database    --offline False 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-05-21T144653.521804.snakemake.log
WorkflowError:
At least one job did not complete successfully.
